# fly.toml app configuration file generated for rental-notice on 2025-04-09T16:51:55-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'rental-notice'
primary_region = 'sea'
# console_command = 'php /var/www/html/artisan tinker'

[mounts]
  source = "rental_notice"
  destination = "/data"

[build]
  [build.args]
    NODE_VERSION = '18'
    PHP_VERSION = '8.2'

[env]
  APP_ENV = 'production'
  LOG_CHANNEL = 'stack'
  LOG_LEVEL = 'debug'
  LOG_STACK = 'stderr,papertrail'
  MAIL_MAILER = 'ses'
  MAIL_FROM_ADDRESS = 'help@oregonpastduerent.com'
  MAIL_FROM_NAME = 'Oregon Past Due Rent'
  LOG_STDERR_FORMATTER = 'Monolog\Formatter\JsonFormatter'
  SESSION_DRIVER = 'database'
  SESSION_SECURE_COOKIE = 'true'
  QUEUE_CONNECTION = 'database'
  DB_CONNECTION = 'sqlite'
  DB_DATABASE = '/data/rental-notice.sqlite'
  AWS_DEFAULT_REGION = 'us-east-1'
  AWS_BUCKET = 'rental-notice'
  PRINT_SERVER_PRINTER = 'Brother_HL_L2405W'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
  memory = '512mb'
